src/Entity/Reservation.php
<?php

namespace App\Entity;

use Assert\LessThan;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ReservationRepository;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\GreaterThanOrEqual('today', message: "Merci de réserver pour aujourd'hui ou plus tard")]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(length: 255)]
    private ?string $reservation_name = null;

    #[ORM\Column(length: 255)]
    private ?string $restaurant_name = null;

    #[ORM\Column]
    #[LessThan(20)]
    private ?int $number = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $heure = null;

    /**
     * @ORM\Column(type="integer", nullable=false, options={"default":0})
     */
    private $vip;

    public function getVip(): bool
    {
        return (bool) $this->vip;
    }

    public function setVip(int $vip): self
    {
        $this->vip = (int) $vip;

        return $this;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getReservationName(): ?string
    {
        return $this->reservation_name;
    }

    public function setReservationName(string $reservation_name): self
    {
        $this->reservation_name = $reservation_name;

        return $this;
    }

    public function getRestaurantName(): ?string
    {
        return $this->restaurant_name;
    }

    public function setRestaurantName(string $restaurant_name): self
    {
        $this->restaurant_name = $restaurant_name;

        return $this;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(int $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getHeure(): ?\DateTimeInterface
    {
        return $this->heure;
    }

    public function setHeure(\DateTimeInterface $heure): self
    {
        $this->heure = $heure;

        return $this;
    }

    // Ceci est une fonction permettant lors du formulaire de réservation de selectionner toutes les tranches de 30 min, entre 11H et 23h30
    // Ca corresponds aux heures d'ouverture du resto
    public function generateHourOptions(): array
{
    $heureOptions = [];
    $h = 10;
    $m = 0;

    // Boucle pour ajouter toutes les heures possibles
    while ($h < 22 || ($h == 22 && $m == 0)) {
        $hour = str_pad($h, 2, '0', STR_PAD_LEFT);
        $min = str_pad($m, 2, '0', STR_PAD_LEFT);
        $heure = new \DateTime("{$hour}:{$min}");
        $heureOptions[$heure->format('H:i')] = $heure;
        $m += 30;
        if ($m == 60) {
            $m = 0;
            $h++;
        }
        // On s'arrête à 23H30
        if ($h == 22 && $m == 0) {
            break;
        }
    }

    return $heureOptions;
}
// public function __toString(){
//     return $this->heure;
// }
}


src/Controller/AdminReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Form\Reservation1Type;
use App\Repository\ReservationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\DBAL\Connection;
use DateTime;

#[Route('/admin/reservation')]
class AdminReservationController extends AbstractController
{
    #[Route('/', name: 'app_admin_reservation_index', methods: ['GET'])]
    public function index(ReservationRepository $reservationRepository,Connection $connection): Response
    {
        // $reservations = $connection->fetchAllAssociative('SELECT DISTINCT date FROM reservation');
        $reservationsDates = $connection->fetchAllAssociative('SELECT DISTINCT date FROM reservation');
        // $today = date('Y-m-d H:i:s');
        // $date = \DateTime::createFromFormat('Y-m-d H:i:s', $today);
        $date = date('Y-m-d H:i:s');

        return $this->render('admin_reservation/index.html.twig', [
            // 'reservations' => $reservationRepository->findAll(),
            'reservations' => $reservationsDates,
            'selectedDate' => $date,
        ]);
    }

    #[Route('/{date}', name: 'app_admin_reservation_select', methods: ['GET'])]
    public function select(ReservationRepository $reservationRepository, Connection $connection, Request $request): Response
    {   
        $dateString = $request->attributes->get('date');
        $query = 'SELECT * FROM reservation WHERE date = :date';
        $selectedReservations = $connection->fetchAllAssociative($query, ['date' => $dateString]);

        $reservationsDates = $connection->fetchAllAssociative('SELECT DISTINCT date FROM reservation');

        return $this->render('admin_reservation/index.html.twig', [
            'reservations' => $reservationsDates,
            'selectedReservations' => $selectedReservations,
            'selectedDate' => $dateString,
        ]);

    }

    #[Route('/new', name: 'app_admin_reservation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ReservationRepository $reservationRepository): Response
    {}
 
    #[Route('/{id}', name: 'app_admin_reservation_show', methods: ['GET'])]
    public function show(Reservation $reservation): Response
    {
        
        return $this->render('admin_reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_admin_reservation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Reservation $reservation, ReservationRepository $reservationRepository): Response
    {
        $form = $this->createForm(Reservation1Type::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reservationRepository->save($reservation, true);
            /////////////////////////////
            return $this->redirectToRoute('admin_reservation_update_confirmation', [], Response::HTTP_SEE_OTHER);
            // return new Response(null, Response::HTTP_SEE_OTHER);
            // return new Response(null, Response::HTTP_NO_CONTENT);

        }

        return $this->renderForm('admin_reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_reservation_delete', methods: ['POST'])]
    public function delete(Request $request, Reservation $reservation, ReservationRepository $reservationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservation->getId(), $request->request->get('_token'))) {
            $reservationRepository->remove($reservation, true);
        }
        //////////////////////
        return $this->redirectToRoute('admin_reservation_delete_confirmation', [], Response::HTTP_SEE_OTHER);
        // return new Response(null, Response::HTTP_SEE_OTHER);
    }
    
}

templates/admin_reservation/_delete_form.html.twig
<style>
    .supprBtn {
        padding: 0.8rem 0.65rem;
        position: absolute;
        bottom: 2.03%;
        right:0.7%;
        margin: 20px 0 0px;
        font-size: 1.2rem!important;
        color: black;
        border-radius: 0;
        text-transform: uppercase;
        border: 3px solid black!important;
        font-weight: 500!important;
        background: rgba(149, 198, 35, .8);
        backdrop-filter: blur(10px);
    }
    .supprBtn:hover {
        border: 3px solid var(--orange)!important;
        text-shadow: 2px 3px 1px var(--orange);
        background: rgba(232, 233, 243, .5);
    }
</style>
<form method="post" action="{{ path('app_admin_reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Voulez-vous supprimer cette réservation?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="supprBtn">Supprimer</button>
</form>



templates/admin_reservation/_form.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
<style>
    body {
    overflow: hidden;
    }
    #bottom {
        display: none!important;
    }
    #reservation1{
        display: flex;
        flex-wrap: wrap;
        height:390px;   
    }
    #form {
        padding: 5rem 1rem;
    }
    .form-wrapper {
        padding: 0.6rem 0.1rem;
        background: white;
    }
    .form-group {
        display: flex;
        justify-content: center;
        margin-top: 5px;
        width: 93vw;
    }
    .form-group, .form-group-vip, .buttons {
        transform: translateX(10px);
    }
    .form-group textarea {
        resize: vertical;
    }
    .btn {
        width: -webkit-max-content;
        width: -moz-max-content;
        width: max-content;
        border: none;
        padding: 0.8rem 0.75rem;
        font-weight: 500;
    }
    .supprBtn {
        padding: 0.8rem 0.45rem;
    }
    .form-check-inpt:checked {
        background-color: var(--yellowGreen);
        color: white;
    }
    .form-check-inpt:focus {
        border: 3px solid var(--yellowGreen);
        background-color: rgba(232, 233, 243, .1); 
        box-shadow: 0px 0px 0px black;
    }
    .form-check-inpt, #reservation1_vip{
        width: 40px;
        padding: 1.5rem;
        border-radius: 0px;
        margin-top: 0.5rem;
        border: 3px solid black;
        background-color: rgba(240, 134, 50, .1);
        background: var(--yellowGreen);
        -webkit-backdrop-filter: blur(20px);
                backdrop-filter: blur(20px);
    }
    .form-group input,
    .form-group textarea,
    .form-group select {
        font-size: 14px;
        padding: 5px;
        border-radius: 0.5px;
        margin-top: 0.5rem;
        border: 1px solid black;
        cursor: pointer;
    }
    .form-group > input:focus , .form-group > *:focus , 
    .form-group > input:hover, select:hover, select:active, .form-group > option,
    .form-control > option {
        border: 0.5px solid #95C623;
        box-shadow: 0px 0px 0px black;
        color: black;
    }
    select {
        text-transform: none;
        word-wrap: normal;
    }
    .form-group > label {
        margin-right: 10px;
    }   
    .form-group label, .form-group-vip > label {
        margin-top: 10px;
    }
    .buttons > * , #reservation1_submit{
        margin: 20px 0 0px;
        font-size: 1.2rem!important;
        color: black;
        border-radius: 0;
        text-transform: uppercase;
        border: 3px solid black!important;
        font-weight: 500!important;
        background: rgba(149, 198, 35, .8);
        -webkit-backdrop-filter: blur(10px);
                backdrop-filter: blur(10px);
    }
    .buttons > *:hover , #reservation1_submit:hover{
        background: rgba(232, 233, 243, .5);
        border: 3px solid var(--yellowGreen)!important;
        text-shadow: 2px 3px 1px var(--yellowGreen);
    }
    form .supprBtn {
        background: var(--orange);
    }
    .form-group input {
        margin: 0;
    }
    #reservation1_date, #reservation1_heure {
        background: none;
        border: none;
    }
    #principal > div > form > label {
        font-size: 8px;
    }
    .form-control, .form-select {
        padding: 1px;
        color: black;
    }
    .buttons {
        display:flex;
        width: 90vw;
    }
    #principal > div > form > div:nth-child(1) > ul > li {
        font-size: 10px;
        list-style-type: none;
        position: absolute;
        z-index: 20!important;
        left: 0;
        top:-23%;
        color: #DD2D4A;
        -webkit-backdrop-filter: blur(10px);
                backdrop-filter: blur(10px);
        padding: 70px auto;
    }
{% include "partials_footer_version_classic.style.twig" %}
</style>
{% endblock %}

{% block body %}
<div class="form-wrapper">
    {{ form_start(form) }}
        <div class="form-group">
            {{ form_label(form.date, 'Date') }}
            {{ form_widget(form.date, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.date) }}
        </div>
        <div class="form-group">
            {{ form_label(form.heure, 'Heure') }}
            {{ form_widget(form.heure, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.heure) }}
        </div>
        <div class="form-group">
            {{ form_label(form.reservation_name, 'Nom') }}
            {{ form_widget(form.reservation_name, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.reservation_name) }}
        </div>
        <div class="form-group">
            {{ form_label(form.restaurant_name, 'Restaurant') }}
            {{ form_widget(form.restaurant_name, {'attr': {'placeholder': 'Restaurant à choisir', 'class': 'form-select'}}) }}
            {{ form_errors(form.restaurant_name) }}
        </div>
        <div class="form-group">
            {{ form_label(form.number, 'Couverts') }}
            {{ form_widget(form.number, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.number) }}
        </div>
        <div class="form-group">
            {{ form_label(form.email) }}
            {{ form_widget(form.email, {'attr': {'placeholder': 'Email', 'class': 'form-control'}}) }}
            {{ form_errors(form.email) }}
        </div>
        {% if is_granted('ROLE_ADMIN') %}
        <div class="form-group-vip">
            {{ form_label(form.vip) }}
            {{ form_widget(form.vip, { 'attr': {'class': 'form-check-inpt'} }) }}
            {{ form_errors(form.vip) }}
        </div>
        {% endif %} 
        
    {{ form_end(form) }}
    {# <div class="buttons">
        <button class="btn">Confirmer</button>

    </div> #}
    

</div>
{% endblock %}

templates/admin_reservation/delete_confirmation.html.twig
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>confirmation de suppression</title>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;1,500&display=swap" rel="stylesheet">
  <style>
    h1{
        font-family: 'Montserrat', sans-serif;
        font-weight: 400;
        margin-top: 80px;
        text-align: center;
        -webkit-animation: visible 200ms ease-out forwards;
                animation: visible 200ms ease-out forwards;
    }
    @-webkit-keyframes visible {
        from {
            opacity:0;
        } 
        to {
            opacity:1;
        }
    }
    @keyframes visible {
        from {
            opacity:0;
        } 
        to {
            opacity:1;
        }
    }
  </style>
</head>
<body>
  <h1>La réservation a bien été supprimée</h1>
</body>
</html>

templates/admin_reservation/edit.html.twig
{# {% extends 'base.html.twig' %} #}

{% block stylesheets %}
<style>
    #edit-wrapper {
        height: 200px;
    }
</style>
{% endblock %}
{% block body %}
    <div id="edit-wrapper">
        {{ include('admin_reservation/_form.html.twig', {'button_label': 'Update'}) }}
        {{ include('admin_reservation/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/admin_reservation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation index{% endblock %}
{% block stylesheets %}
{% include "partials_footer_version_classic.style.twig"%}
<style>
    body {
        background: none !important;
        width: 100vw;
    }

    #zig-zags::after {
        display: none;
    }

    .container {
        margin-top: 180px !important;
        height: 100vh;
        text-align: center;
        -webkit-animation: popUp 0ms !important;
                animation: popUp 0ms !important;
        display: flex;
        flex-direction: column;
        margin-bottom: 50px;
    }

    #admins {
        position: fixed;
    }

    .buttons {
        display: flex;
        justify-content: space-between;
        padding-bottom: 30px;
        position: relative;
        margin-bottom: 20px;
    }

    .rsrvButton,
    .btn,
    .btn-secondary,
    .dropdown-toggle {
        font-size: 1.3rem !important;
        color: black;
        border: 3px solid rgba(17, 17, 17, .6) !important;
        font-weight: 500 !important;
        background: rgba(149, 198, 35, .8);
        -webkit-backdrop-filter: blur(10px);
                backdrop-filter: blur(10px);
        padding: .7rem;
        border-radius: 0;
    }

    .rsrvButton a,
    .btn-secondary a,
    .btn-secondary:hover a {
        color: black;
    }

    .rsrvButton:hover,
    .btn-secondary:hover,
    .btn-secondary:active {
        color: black;
        background: rgba(232, 233, 243, .5);
        border: 3px solid var(--yellowGreen) !important;
        text-shadow: 2px 2px 1px var(--yellowGreen);
    }

    .buttons::after {
        background: var(--orange);
        position: absolute;
        width: 80%;
        height: 1px;
        content: '';
        bottom: 0;
        left: 10%;
    }

    .dropdown-menu,
    .show {
        border-radius: 0;
        text-align: center;
        --bs-dropdown-link-active-bg: #95C623;
    }

    #dropdownMenuButton {
        padding: 0.7rem 14px;
    }

    #admins>table>tbody>tr>td {
        padding: 5px;
    }

    #admins>table>thead>tr>th,
    #admins>table>tbody>tr>td {
        padding-left: 15px;
        font-size: 20px;
    }

    table>thead,
    table>tbody,
    #admins {
        width: 900px;
    }

    #principal>div>table>tbody>tr {
        opacity: 0;
    }

    #principal>div>table>tbody {
        overflow-x: scroll;
    }

    .makeVisible {
        -webkit-animation: visible 80ms forwards calc(var(--order)*40ms) !important;
                animation: visible 80ms forwards calc(var(--order)*40ms) !important;
    }

    #admins>table>tbody>tr>td:nth-child(6) {
        text-align: center;
    }

    #edit,
    #star {
        height: 30px;
    }

    #star {
        margin-right: -35px;
    }

    #principal>div>table>tbody {
        overflow: hidden;
    }

    #admins>table {
        position: relative !important;
        z-index: -5 !important;
    }

    #admins>table>tbody>tr>td {
        padding-left: 3px;
    }

    #reservation-iframe,
    #admins>table>tbody>tr>td>iframe {
        position: absolute;
        inset: 0;
        margin: auto;
        display: none;
        scale: 1.5;
        z-index: 10 !important;
        background-color: white;
        height: 390px;
        transform: translateY(15%);
        overflow: hidden;
        box-shadow: 2px 2px 10px rgba(221, 45, 74, .5);
        -webkit-animation: visible 200ms ease-out;
                animation: visible 200ms ease-out;
    }

    #cross {
        cursor: pointer;
        position: absolute;
        inset: 0;
        margin: auto;
        display: none;
        z-index: 11 !important;
        transform: translate(380%, -340%);
    }

    .unvisible {
        display: none;
    }

    @media screen and (max-width: 750px) {
        .container {
            display: block;
        }
        table {
            display: flex;
            flex-direction: column;
            justify-content: center;
            margin-left: 0;
            {# position: unset!important; #}
            z-index: -30!important;
        }
        #admins {
            width: 100vw;
            height: 100vh;
        }
        .buttons {
            margin-top: 30px;
        }
        #dropdownMenuButton {
            padding: 0.7rem 11px;
        }
        #admins>table {
            width: 100vw;
        }
        #admins>table>tbody>tr>td {
            font-size: 14px;
        }
        #admins>table>thead>tr>th {
            font-size: 12px;
            padding-left: 9px;
        }
        #admins > table > thead > tr,
        #admins > table > tbody > th {
            width: 100vw;
            display: flex;
            justify-content: space-evenly;
        }
        .rsrvButton, .btn, .btn-secondary, .dropdown-toggle {
        font-size: 1rem !important;
        padding: 0.7rem;
        }
        #admins > table > tbody > tr > td:nth-child(4) {
            padding: auto 20px;
        }
        #star {
            margin-right: 0px;
            height: 20px;
        }
        #edit {
            height: 15px;
        }
        #reservation-iframe, #admins>table>tbody>tr>td>iframe {
            scale: 1.3;
            top: -165px;
        }
        #cross {
            scale: .8;
            top: -165px;
        }
    }

    @media screen and (max-width: 530px) {
        .dropdown-menu {
        --bs-dropdown-min-width: auto;
        --bs-dropdown-padding-x: 5px;
        --bs-dropdown-padding-y: 10px;
        }

        .buttons {
            width:100vw;
            justify-content: center;
            gap: 4px;
            transform: translateX(-10px);
        }

        table {
            margin-left: -10px;
        }

        table>thead,
        table>tbody {
            width: 100vw;
        }

    }
</style>
{% endblock %}

{% block body %}
{% include "partials_nav.html.twig"%}
<div class="container" id="admins">
    <h1>Réservations</h1>
    <div class="buttons">
        <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{selectedDate|date('d.m.Y')}}
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <form action={{path('app_admin_reservation_index_select')}}  method="get" id="choosenDatesForm">
                {% for r in reservations %}
                    <a class="dropdown-item" href="{{r.date}}">{{r.date|date('d.m.Y')}}</a>
                    {# <a class="dropdown-item" href="{{r.date}}">{{ r.date|date('Y-m-d')}}</a> #}
                {% endfor %}
            </form>
        </div>
        </div>
        <button class="rsrvButton" type="button" aria-expanded="false"><a href="{{ path('app_reservation') }}">Nouvelle réservation</a></button>
    </div>
    {# <h2>Réservations pour la date {{selectedDate|date('Y-m-d')}}</h2> #}
    
{% if selectedReservations is defined and selectedReservations|length > 0 %}
    {% set sortedReservations = selectedReservations|sort((a, b) => a.heure <=> b.heure) %}
    <table>
        <thead>
            <tr>
                <th>Heure</th>
                <th>Nom</th>
                <th>Restaurant</th>
                <th>Couverts</th>
                <th>E-mail</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for selected in sortedReservations %}
                <tr>
                    <td>{{ selected.heure|date('H:i') }}</td>
                    <td>{{ selected.reservation_name }}</td>
                    <td>{{ selected.restaurant_name }}</td>
                    <td>{{ selected.number }}
                        {% if selected.vip == 1 %}
                        <img id="star" src="{{ asset('IMG/star.svg') }}" alt="vip_mark">
                        {% endif %}
                    </td>
                    <td>{{ selected.email }}</td> 
                    <td id="toShowIframe">  
                        <a href="#" onclick="showIframe()">
                            <img id="edit" src="{{ asset('IMG/edit.svg')}}" alt="edit">
                        </a>
                        <iframe id="reservation-iframe" src="{{ path('app_admin_reservation_edit', {'id': selected.id}) }}">
                        </iframe>
                        <img  style ="width:50px;" onclick="closeIframe()" id="cross" src="{{ asset('IMG/close.svg')}}" alt="closing_cross"/>
                    </td>
                </tr> 
            {% endfor %}
        </tbody>
    </table>
{% else %}
<h3>Pas de réservations pour cette date</h3>
{% endif %}
</div>
{% endblock %}

{% block javascripts %}
    <script>
    const TABLE = document.querySelectorAll("#principal > div > table > tbody > tr");
    let rows = TABLE.length;
    for(i = 0; i < rows; i++) {
        TABLE[i].setAttribute("style", `--order:${i}`);
        if(i % 2 === 0) {
        TABLE[i].style.background = "rgba(149, 198, 35, .45)";
        }
    };

    TABLE.forEach(function(tbl) {
    tbl.classList.add("makeVisible");
    });
    
    
    
    </script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script>
        /*const CLOSER = document.querySelector("#edit-wrapper > a");*/
        let editImg = document.querySelectorAll("#toShowIframe > a");
        let toBlur = document.querySelectorAll('h1, button, .buttons, thead, #footer>div');
        let toHide = document.querySelectorAll('table > tbody > tr > td:not(td:nth-child(6))');
        let backGround = document.querySelectorAll("#admins > table > tbody > tr");

        const anchors = document.querySelectorAll("#toShowIframe > a");
        anchors.forEach(function(anchor) {
        anchor.addEventListener('click', function() {   
            const iframe = this.nextElementSibling;
            const cross = iframe.nextElementSibling;
            iframe.style.display = 'block';
            iframe.style.filter = 'none';
            cross.style.display = "block";
            cross.style.filter = "none";
        });
        });

        function showIframe(){
            toHide.forEach(function(hide){
                hide.classList.toggle("unvisible");
            }); 
            backGround.forEach(function(bckGrnd){
                bckGrnd.style.background = "none";
            });
            editImg.forEach(function(edtImg){
                edtImg.classList.toggle("unvisible");
            });
            toBlur.forEach(function(toBlr){
                toBlr.style.filter = "blur(1rem)";
            });
        };
        function restoreTable() {
            toHide.forEach(function(hide){
                hide.classList.remove("unvisible");
            }); 
        }
        function closeIframe() {
            location.reload(true);
        };     
    </script>
{% endblock %}



templates/admin_reservation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
    <h1>Reservation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reservation.id }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ reservation.date ? reservation.date|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Reservation_name</th>
                <td>{{ reservation.reservationName }}</td>
            </tr>
            <tr>
                <th>Restaurant_name</th>
                <td>{{ reservation.restaurantName }}</td>
            </tr>
            <tr>
                <th>Number</th>
                <td>{{ reservation.number }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ reservation.email }}</td>
            </tr>
            <tr>
                <th>Heure</th>
                <td>{{ reservation.heure ? reservation.heure|date('H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_admin_reservation_index') }}">back to list</a>

    <a href="{{ path('app_admin_reservation_edit', {'id': reservation.id}) }}">edit</a>

    {{ include('admin_reservation/_delete_form.html.twig') }}
{% endblock %}